"""Notifications with Enum

Revision ID: 46c55a98cd70
Revises: f8cde1405912
Create Date: 2025-08-23 18:16:47.829404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c55a98cd70'
down_revision: Union[str, Sequence[str], None] = 'f8cde1405912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('status', sa.Enum('UNREAD', 'READ', name='status'), nullable=True))
    op.drop_column('notifications', 'channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'status')
    # ### end Alembic commands ###
