"""Now user has a telegram handler

Revision ID: 4ebf5678e5b2
Revises: 44c60cdfb9cb
Create Date: 2025-08-21 01:34:55.941706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebf5678e5b2'
down_revision: Union[str, Sequence[str], None] = '44c60cdfb9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_handler', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_handler')
    # ### end Alembic commands ###
