"""Now cartitems has price

Revision ID: 7e865d9d4c19
Revises: 986cc21a62c1
Create Date: 2025-08-20 22:40:25.377502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e865d9d4c19'
down_revision: Union[str, Sequence[str], None] = '986cc21a62c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    # ### end Alembic commands ###
